#####################
## topic modeling ##
####################

ifelse(!require("tidyverse"), install.packages("tidyverse"), require(tidyverse))
ifelse(!require("quanteda"), install.packages("quanteda"), require(quanteda))
ifelse(!require("stm"), install.packages("stm"), require(quanteda))
source("functions/dfm_splitgrams.R")
source("functions/do_preprocessing.R")
source("functions/get_topdocs.R")

# load data
dfm_combined_nd <- url("https://campuscloud.unibe.ch:443/ssf/s/readFile/share/24121/-5995487485071316790/publicLink/dfm_combined_nd.RData")
load(dfm_combined_nd)

# do preprocessing (in that order)
  # all to lower
  # split ngrams
  # removal of features with less than 3 characters
  # removal of stopwords
  # stemming (using Martin Porter's stemming algorithm and the C libstemmer library generated by Snowball)
  # relative pruning (remove features that appear in less than 0.5% and in more than 99% of all documents)
dfm <- do_preprocessing(dfm.combined.nd)

# convert dfm to stm format
stm <- convert(dfm, to = "stm")
save(stm, file = "data/stm_dfm.RData")

# determine optimal numbber of topics
determine_k <- searchK(stm$documents, stm$vocab, K = c(5,10,15,20,25,30,35,40), cores = 2)
pdf("tm/determine_k.pdf")
plot(determine_k)
dev.off()

# estimate stm (K = 20)
stm.k20 <- selectModel(documents = stm$documents, vocab = stm$vocab, K = 20, runs = 20, max.em.its = 300, init.type = "LDA", seed = 1234, verbose = TRUE)
save(stm.k20, file = "tm/stm_k20.RData")

# select best model
pdf("tm/select_model.pdf")
plotModels(stm.k20)
dev.off()
stm.k20.sel <- stm.k20$runout[[4]]
save(stm.k20.sel, file = "tm/stm_k20_select.RData")

# get topic topwords (n = 10)
topwords <- data.frame(t_id = paste0("t_", 1:20),
                       topwords = apply(sageLabels(stm.k20.sel, n = 10)$marginal$prob, 1, paste, collapse = ", "))
write.csv(topwords, file = "tm/topwords.csv", row.names = FALSE)

# prepare documents for selection of topdocs
data_online <- url("https://campuscloud.unibe.ch:443/ssf/s/readFile/share/24056/-1422573848356377275/publicLink/data_online.RData")
load(data_online)
data_offline <- url("https://campuscloud.unibe.ch:443/ssf/s/readFile/share/24081/-6801514032582368813/publicLink/data_offline.RData")
load(data_offline)
texts <- rbind(select(data.offdata, d_id, text),
               select(data.ondata, d_id, text))
texts <- filter(texts, d_id %in% names(stm$documents))
texts <- texts[match(names(stm$documents), texts$d_id), ]

# get topdocs (n = 10, thresh = 0.6)
topdocs <- get_topdocs(stm.k20.sel, texts, 10, 0.6)
write.csv(topdocs, file = "tm/topdocs.csv", row.names = FALSE)
